version: "2.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8098:8098"
    command: java -Djava.security.egd=file:/dev/./urandom -jar method-tracking.jar